# -*- coding: utf-8 -*-
"""iris1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysajIlW2aISKAili8pJxytG6MM6ctT8S
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical
#import pandas as pd

#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
#df = pd.read_csv(url, header=None, names=column_names)
#X = df.drop('species', axis=1)
#y = df['species']
iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=120, random_state=42, stratify=y)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

sgd = SGD(learning_rate=0.1, momentum=0.9)

model = keras.models.Sequential()
model.add(keras.layers.Dense(5, activation='relu', input_shape=(4,)))
model.add(keras.layers.Dense(5, activation='relu'))
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100)
model.evaluate(X_test, y_test)

